.asf.yaml
=> Prevent force pushes to main

r/content/index.Rmd, r/scripts/install_dependencies.R
Fixes #17 and removes 2 unnecessary dependencies
=> #17 no pacman

.github/workflows/deploy_cookbooks.yml, .github/workflows/test_cookbooks.yml
Fixes #19 and runs the CI on pull requests as well as pushes
=> Also run CI on pull requests to the main branch

.asf.yaml
Thsi gives `thisisnic` and `amol-` the ability to "assign, edit, and close issues and pull requests".  Given their help so far I think this should be pretty straightforward.
=> Adding thisisnic and amol- as collaborators

.asf.yaml
=> Setting up notifications via the ML of git activity

.asf.yaml, .github/workflows/deploy_cookbooks.yml
Very similar to #28 but adds the subdir.
=> Add Apache publishing / hosting

cpp/.clang-format, cpp/code/.clang-tidy, cpp/code/CMakeLists.txt, cpp/code/common.cc, cpp/code/common.h
Addresses #25 
Might be a little strict to start with but we can see how it goes.
=> Added clang-format and clang-tidy files.  Added clang-tidy to the build.

python/source/io.rst
https://issues.apache.org/jira/browse/ARROW-13708
=> Recipe to read line delimited json as of ARROW-13708

python/source/create.rst
https://issues.apache.org/jira/browse/ARROW-13715
=> Creating tables recipe

python/source/create.rst
https://issues.apache.org/jira/browse/ARROW-13717
=> ARROW-13717: Creating arrays recipe

.asf.yaml
Nic is now a committer and should have the permissions automatically.
=> Remove nic from collaborators list

python/source/index.rst, python/source/schema.rst
https://issues.apache.org/jira/browse/ARROW-13721
=> ARROW-13721: Specifying schemas for arrays and tables

python/source/create.rst
https://issues.apache.org/jira/browse/ARROW-13716
=> ARROW-13716: Add RecordBatch recipe

r/content/reading_and_writing_data.Rmd
=> Use as.data.frame instead of dplyr::collect

python/source/create.rst, python/source/schema.rst
https://issues.apache.org/jira/browse/ARROW-13725
=> ARROW-13725: Unify schemas recipe

python/source/data.rst
https://issues.apache.org/jira/browse/ARROW-13727
=> ARROW-13727: Recipe to concatenate two tables

python/source/data.rst
https://issues.apache.org/jira/browse/ARROW-13751
=> ARROW-13751: Recipe for searching for values matching a predicate

CONTRIBUTING.md, README.rst
These comments are from @amol- and edited a bit. Closed #116.
=> Describe recipes and differentiate from user guides

r/CONTRIBUTING.md, r/content/creating_arrow_objects.Rmd, r/content/python.Rmd, r/content/reading_and_writing_data.Rmd, r/content/specify_data_types_and_schemas.Rmd, r/content/tables.Rmd
=> Swap all instances of Table$create for arrow_table

r/content/arrays.Rmd
Minor edit to fix hyper link at the bottom of the page.
=> Fix hyperlink

python/source/flight.rst
=> [Python] Add Flight streaming example

r/content/reading_and_writing_data.Rmd
Add blank line to format bulleted list correctly
=> Update reading_and_writing_data.Rmd (formatting)

cpp/code/datasets.cc
=> [C++] Removed call to UseAsync

cpp/code/CMakeLists.txt, cpp/code/common.cc, cpp/code/flight.cc, cpp/source/flight.rst, cpp/source/index.rst
Also fixes a bug(?) with merging outputs.
Fixes #122.
=> [C++][Flight] Add basic Flight service

python/source/flight.rst
=> [Python][Flight] Add an 'HTTP basic auth' example

cpp/source/conf.py, java/source/conf.py, python/source/conf.py
=> [Python][Java][C++] Make the sphinx docs wide enough for code examples

python/source/data.rst
This PR includes a new section to address the issue: https://github.com/apache/arrow-cookbook/issues/110
=> [Python] Add a Python Cookbook recipe on group_by + sort

.github/workflows/test_java_linux_cookbook.yml, .github/workflows/test_java_osx_cookbook.yml, java/ext/javadoctest.py
Initial changes to support Arrow Java code with JSE17/18
=> ARROW-16291: [Java] Support JSE17 for Java Cookbooks

CONTRIBUTING.md
=> [Java] Fixing broken link in CONTRIBUTING.md for Java

r/content/arrays.Rmd
Fixes #201 by removing extraneous test
=> Remove unnecessary extra test which is causing build failure

java/source/create.rst, java/source/io.rst
=> [Java] Adding examples about Dictionary-encoded Layout

java/source/flight.rst
=> [Java] Fix memory management issues in Flight example

cpp/source/conf.py, python/source/conf.py
Also, it appears my editor ran `black` on these files when I saved them, so there are a few style changes too. Happy to back those out if anyone feels strongly about it.
=> MINOR: update copyright year to 2022

java/source/schema.rst
Minor fix - added missing semicolon for create Fields section. 
The code passes with make javatest, however found the issue when copy pasting into editor showed error.
=> [Java] Added missing semicolon in Working with Schema page

java/source/create.rst, java/source/data.rst, java/source/dataset.rst, java/source/demo/pom.xml, java/source/index.rst, java/source/io.rst, java/source/schema.rst
Added missing License headers to files in java cookbook
=> [Java] Added missing license headers

java/source/create.rst
Added an example to show splicing on IntVector
=> [Java] Added splicing example for IntVector

cpp/CONTRIBUTING.md
Updated the formatting to display hyperlink correctly
=> [CPP] Updated the hyperlink formatting for Code of Conduct

java/source/create.rst
Added example for splicing from a non-zero index
=> [Java] Add splicing non-zero index example

CONTRIBUTING.md, README.rst, cpp/CONTRIBUTING.md, cpp/code/datasets.cc, java/CONTRIBUTING.rst
Found few more files with missing license.
=> Added missing license

.github/workflows/deploy_development_cookbooks.yml, .github/workflows/deploy_stable_cookbooks.yml, .github/workflows/test_arrow_nightly_cookbook.yml, .github/workflows/test_r_cookbook.yml
=> GH-286: [R] Revert installing more dependencies for using nightly packages

python/requirements.txt, python/source/flight.rst
=> [Python][Flight] Show how to propagate opentelemetry spans to Flight

java/ext/javadoctest.py
=> GH-290: [Java][CI] Fix typing annotation imports

r/content/datasets.Rmd, r/content/reading_and_writing_data.Rmd
=> [R] Fix test failures on main

r/content/tables.Rmd, r/scripts/install_dependencies.R
apache/arrow#35779 and apache/arrow#35709 document how to perform window aggregates
It was discussed on the mailing list: https://lists.apache.org/thread/b16ghtb8q9hyl64ks3dp9ftm7pvlnsdk to document this operation in the vignette and in the cookbook.  Now that these are documented in the vignettes I thought I'd add them to the cookbook. Let me know what you think.
=> [R] Document window aggregates

python/source/schema.rst
This PR closes https://github.com/apache/arrow-cookbook/issues/331
=> [Python] Fix error in schema examples (pa.unify_schemas) for dev arrow version

java/source/conf.py, java/source/demo/pom.xml, java/source/substrait.rst
To closes https://github.com/apache/arrow-cookbook/issues/340
=> [Java] A cookbook for reading datasets and applying filters and projections

dev/release/01-bump-versions.sh, dev/release/README.md, dev/release/utils-prepare.sh
Fixes https://github.com/apache/arrow-cookbook/issues/372. See included README changes for the new workflow. I also took this time to clean up the README a bit.
=> [Release] Update release process for separate Java
