apache/arrow-cookbook

.github/workflows/deploy_cookbooks.yml
This PR refactors the checkout-and-deploy job so it no longer uses a third party GH Action (which are not allowed on Apache repos unless specifically authorised)
=> Refactor GH Actions job that uses third party action

.asf.yaml
This PR adds config settings necessary to have issues enabled on this repo as well as the gh-pages branch for publishing the cookbook (as described here: https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-Repositoryfeatures)
=>  Enable issues & gh-pages branch on Github repo #5 

.asf.yaml
This PR removes the second "github" section header from the config file and adds the Apache license
=> remove duplicated sections and add ASF license in .asf.yaml

.github/workflows/deploy_cookbooks.yml
Right now the deploy operation checks out the current gh-pages branch, does a `git add *` to update it, and then pushes it.  However, this has some downsides, most of which could be worked around with more complexity:
* If files are removed they won't disappear from gh-pages.
* If binary files (e.g. images, test data) change often they can clutter up the git repo (this is kind of an argument against any impl of gh-pages though)
* If no files changed it can fail the build because the commit / push will fail
An alternative method is to just force push a brand new branch with a single commit every single time which is what this PR does.
=> Change gh-pages deploy to a single commit

.asf.yaml, r/scripts/install_dependencies.R
Fixes #13   - When installing the R dependencies, the default behaviour is now to install the latest released version of the Arrow R package.
=> #13 install latest release

r/scripts/install_dependencies.R
This PR prevents existing environment variables from interfering with build process when run locally
=> [R] Fix Arrow C++ version that is installed

.asf.yaml
ASF Infra has a regex to test if a username is a valid GH username.  GH does not allow usernames to end in hyphen.  However, they did allow this at one point and they grandfathered in some names.  ASF Infra is rejecting these grandfathered in names.
=> Temporarily removing collaborators ending in -

.github/workflows/deploy_cookbooks.yml
I think the reason the deploy didn't work was because the .asf.yaml file has to be on the asf-site branch.  This PR changes that.  It also tweaks the orphan-deploy process a little bit because the old one was leaving behind cached files.  Now it removes all files, downloads the book, then uploads everything.
=> Copy .asf.yaml to asf-site branch

python/source/io.rst
Hi, I have started playing with the cookbook examples and there is a little doc section that I did not find clear hence here this PR.
The **testsetup::** blocs in the rst files are not written out in the resulting HTML.
In the "Given an array with 100 numbers, from 0 to 99" sections the **arr** object pops up ex nihilo in the documentation which might lose the reader a bit even though most people will guess the np.arange here.
Add the array creation code in the testcode:: blocs for those sections section to make it more explicit.
That is going from
```
Given an array with 100 numbers, from 0 to 99
print(f"{arr[0]} .. {arr[-1]}")
0 .. 99
```
to
```
Given an array with 100 numbers, from 0 to 99
import numpy as np
import pyarrow as pa
arr = pa.array(np.arange(100))
print(f"{arr[0]} .. …
```
=> Explicit arr object creation

r/content/reading_and_writing_data.Rmd
The data frames in question are only 3 lines long, so you don't need them.
=> [R] Remove unnecessary head()s

python/source/io.rst
=> Writing Partitioned Datasets recipe for Python

python/source/io.rst
Addresses https://github.com/apache/arrow-cookbook/pull/49
=> Update CSV recipe to use pyarrow.csv instead of pandas

python/source/io.rst
Without the `anonymous=True` flag I was not able to read data from the `ursa-labs-taxi-data` S3 bucket. I updated the S3 section so this should work every time.
=> Adding anonymous flag to s3

README.rst
Sorry, I'm poking around and happened to spot little things like this.
=> Fix Markdown/Jira-style links in README.rst

cpp/CONTRIBUTING.md, cpp/code/.clang-tidy, cpp/code/CMakeLists.txt, cpp/code/datasets.cc, cpp/environment.yml
I had to add UseAsync back in, as its removal was based on 7.0.0, which is a touch premature as 7.0.0 is not in conda yet.  It was ok to be removed in 5.0.0 but in 6.0.1 we don't support non-async dataset writes and so the dataset write example was failing.
=> [C++] Drop gtest to 1.10 / Raise Arrow to 6.0.1

python/source/flight.rst
Use a temporary directory instead of the current working directory.
Also, remove calls to FlightServerBase.serve() (they're unnecessary
since the server is active as soon as it's created).
Fixes #141.
=> [Python] Make Flight tests idempotent

python/source/create.rst, python/source/flight.rst
- Minor capitalisation fix in create.rst
- User example of how to set up an arrow server using self-signed certificates
=> Include Python Server Client Example with Certificates

r/CONTRIBUTING.md
– list dependencies
– move mention of {arrow} dependency/build to list above
– add path hint if `bookdown` cannot find `pandoc` when shipped with RStudio
=> [R] Add list of dependencies and hint for global pandoc path in CONTRIBUTING.md

java/source/dataset.rst, java/source/demo/pom.xml
PR to fix problems mention at: https://github.com/apache/arrow-cookbook/issues/206
=> [Java] Parquet reading example fails with Arrow v8.0

python/source/create.rst
Just a little PR to add an example of how to make a Table from a list of rows with [`pyarrow.Table.from_pylist()`](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.from_pylist). 
- I put this in the same "Create Table from Plain Types" section because it already contains an example of the complementary operation of making a Table from a dict, but we can split them out if it's preferable.
- My editor stripped a little trailing whitespace elsewhere, so apologies for the whitespace diffs, but that should reduce future whitespace diffs.
- Built everything, and it looked as expected and links worked.
=> Add example for pa.Table.from_pylist

build/index.html
It would be nice if the Rust examples were easier to find / discover.
Closes https://github.com/apache/arrow-cookbook/issues/182
As suggested by @westonpace  and @yuribudilov on  https://github.com/apache/arrow-cookbook/issues/182#issuecomment-1097357772 add a link to the Rust examples
Upon review, the rust examples could be improved as well -- I will file a follow on ticket for that work
=> Add link to Rust examples

r/content/tables.Rmd
This PR removes information which is incorrect as of v 9.0.0 of Arrow
=> [R] Remove no-longer-true content on calling functions

r/content/arrays.Rmd, r/content/creating_arrow_objects.Rmd, r/content/flight.Rmd, r/content/python.Rmd, r/content/reading_and_writing_data.Rmd, r/content/specify_data_types_and_schemas.Rmd, r/content/tables.Rmd
Added License Headers to R module
Adding to index.rmd causes build failure, hence excluded from this PR
=> Added License Headers to R module

.github/workflows/test_cpp_cookbook.yml, cpp/CONTRIBUTING.md, cpp/code/CMakeLists.txt, cpp/dev.yml
This PR is the first one to be able to build the different cookbooks against the latest development version of Arrow using the Nightly built packages.
Once we can build the different cookbooks with both a stable release and the Nightly version we will be able to deploy a development version of the cookbooks.
This PR also fixes our CMake build to be compatible with the new and old versions
=> [C++] Add C++ build against Arrow Nightlies version

java/source/create.rst
The word "splice" was inadvertently written instead of "slice" in a few places. Changed the text
=> [Java] Update create.rst to address typos: "slice" was written as "splice" #259

.github/workflows/test_arrow_nightly_cookbook.yml, .github/workflows/test_cpp_cookbook.yml, .github/workflows/test_java_linux_cookbook.yml, .github/workflows/test_java_osx_cookbook.yml, .github/workflows/test_python_cookbook.yml, .github/workflows/test_r_cookbook.yml
Currently we are running both tests against the stable and development versions of Arrow on PRs this might cause some issues if working against the current stable version. The idea is to add a stable branch in the future and deploy that one but on the meantime we should only run on CI against arrow dev on demand or as a scheduled task.
=> [CI] Run cookbook recipes against arrow nightlies only manually and scheduled

.asf.yaml, CONTRIBUTING.md
I did not find any documentation on how we merge on the Cookbooks. I thought it might be worth to add a note for committers.
I've also configured the repo to only allow `Squash and merge` to be consistent.
As reference this is the same configuration as arrow/adbc: https://github.com/apache/arrow-adbc/blob/main/.asf.yaml#L19-L22
I've also added the notification on opened and closed issues to the issues ML as we have for other repos.
=> [Dev] Configure merge to only allow Squash and merge

.github/workflows/deploy_cookbooks.yml, .github/workflows/test_arrow_nightly_cookbook.yml, .github/workflows/test_cpp_cookbook.yml, .github/workflows/test_python_cookbook.yml
I think the last deploy failed due to an old `setup-r` action version.
This PR updates the following actions versions:
- `checkout@v3`
- `setup-r@v2`
- `setup-pandoc@v2`
- `upload-artifact@v3`
=> Update actions versions for GitHub and R lib actions

build/index.html, cpp/source/_templates/layout.html, java/source/_templates/layout.html, matomo.html, python/source/_templates/layout.html, r/content/_bookdown.yml
Similar to what we did for the main arrow docs in https://github.com/apache/arrow/pull/13096. 
I tested it locally for the python version (and setup is exactly the same for cpp and java, all identical sphinx sites). ~I am not sure what the equivalent would be for R (since we are using bookdown and not pkgdown as for the main arrow docs, and I don't directly see the same option in bookdown)~ I have added it to R bookdown as well (based on how we did it for the main docs), but haven't tested this myself.
=> Add Matomo Analytics to cookbook

java/source/data.rst, java/source/flight.rst
=> GH-317: [Java] add recipe for vector schema root appender cases

java/source/flight.rst
This PR is against stable (which uses 14.0.0). main should contain that change as it is tested against the dev version of Arrow.
=> [Flight] appMetadata is not expected on 14.0.0 but it is on dev

cpp/environment.yml, python/requirements.txt
We did not update the cookbooks from 12.0.0 to 13.0.0 and when updating from 12.0.0 to 14.0.0 the script missed the following version updates because I used:
`./dev/release/01-bump-versions.sh 13.0.0 14.0.0` instead of `./dev/release/01-bump-versions.sh 12.0.0 14.0.0`
Manually update the missing updates to run cookbooks consistently for 14.0.0.
This commit will have to be cherry-picked to the `stable` branch once merged.
=> [Release] Update wrong arrow and pyarrow versions to 14.0.0

java/ext/javadoctest.py, java/source/avro.rst, java/source/conf.py, java/source/create.rst, java/source/demo/pom.xml
To closes https://github.com/apache/arrow-cookbook/issues/338
=> GH-338: [Java][CI] Upgrade Arrow Java version for Java Cookbooks

cpp/source/conf.py, java/source/conf.py, python/source/conf.py
While looking at the cookbooks I noticed the user doesn't have any way to navigate from an individual cookbook back up to the list of cookbooks. Part or all of the reason for this is probably that, at the source code level, each cookbook is managed as a separate Sphinx build. It's a minor thing, but this PR adds an "All Cookbooks" link below the User Guide and API Reference links in the sidebar to each cookbook.
Before:
After:
I opted to use a relative link instead of an absolute one so the link works locally and on preview builds but let me know if that should be changed.
=> MINOR: [C++][Python][Java] Add "All Cookbooks" link to each cookbook sidebar

.github/dependabot.yml, .github/workflows/deploy_development_cookbooks.yml, .github/workflows/deploy_stable_cookbooks.yml, .github/workflows/test_arrow_nightly_cookbook.yml, .github/workflows/test_cpp_cookbook.yml
The artifact actions of <v3 will be removed soon. To avoid PR spam but also keep actions decently up-to-date I have added a dependabot.yml.
=> MINOR: Bump `actions/*-artifact` to v4 and enable dependabot

java/ext/javadoctest.py
Without --batch-mode, we can sometimes get ANSI escape sequences in the input which makes downstream processing more complicated.
Fixes #363
=> GH-363: [Java] Run maven in batch mode

r/scripts/test.R
I'm somewhat confident this will fix the CI issue on the stable branch we're seeing in https://github.com/apache/arrow-cookbook/issues/381.
I did some testing on draft PRs.
=> GH-381: [R] Use RETICULATE_PYTHON="managed" in test.R
